### ISSUE TITLE
Extension not working (assignment to undeclared variable extension at line 209)

### ISSUE THREAD

**Issue by addadi** [arelange/gnome-shell-extension-hibernate-status#1]
Hi,
i'm using the extension from extensions.gnome.org site (version 4) with gnome-shell 3.12 and the hibernate button doesn't appear. I see in the gnome-session-GNOME.log the following line:
Gjs-Message: JS WARNING: [/home/USERNAME/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js 209]: assignment to undeclared variable extension
To my understanding it means that it didn't succeed in creating an object from the Extension class and instantiate it.
thanks

**Comment by markkrj** [comment]
Affecting me too

**Comment by arelange** [comment]
Removed gnome-shell 3.12 as supported in current version. Gnome website should now fallback 3.12 users to extension version 3.

**Comment by fthiery** [comment]
Hi 

Having the same warning on 3.18, but it does work (button is displayed and has the expected effect).

gnome-session[693]: Gjs-Message: JS WARNING: [/usr/share/gnome-shell/extensions/hibernate-status@dromi/extension.js 209]: assignment to undeclared variable extension

**Comment by xenithorb** [comment]
Getting this on Fedora 23 now that it has been released with 3.18. Hibernate does not operate properly. All of the buttons and modals are displayed properly, but clicking the final hibernate action has no effect.

**Comment by arelange** [comment]
Warning is fixed in commit 365a130
