### ISSUE TITLE
UI is bad

### ISSUE THREAD

**Issue by rugk** [arelange/gnome-shell-extension-hibernate-status#10]
![baduihibernate](https://cloud.githubusercontent.com/assets/11966684/19206945/d4aa00a6-8cec-11e6-8fad-13ce330ad30e.png)

The buttons are not distributed regularly. It looks as if the new button is just "pushed between" these three buttons.

Additionally it would be more useful to have (as the last two right buttons):
- by default the button standby + shutdown
- with alt: hibernate + hybrid sleep

The reason for this is easy:  As currently the standby button is only shown in the alt mode (as it is GNOME's default) one can easier hibernate than standby. Usually, however, users are more likely to standby than to hibernate and hibernation is rather a rarely used "alternative".

If you decide to implement config options it would of course be useful to have a setting where you can configure the buttons in more details.

**Comment by smac89** [comment]
It might have to do with the theme you're using, but I don't notice this on my installation:

![screenshot from 2016-12-24 00-33-43](https://cloud.githubusercontent.com/assets/8305511/21465631/cb792352-c970-11e6-89b2-55a3eeff270d.png)

They all seem to align very well. I am using [Arc theme](https://github.com/horst3180/arc-theme)

**Comment by rugk** [comment]
I am actually just using the default Adwaita theme.

**Comment by p91paul** [comment]
This should probably be closed as layout changed in recent gnome shell (there is now one less button)
