### ISSUE TITLE
No more hibernate possible: "Object has been already disposed"

### ISSUE THREAD

**Issue by theraser** [arelange/gnome-shell-extension-hibernate-status#101]
I'm using this extension for a long time without problems (thanks for this!), hibernating was working fine for months. But since a few weeks I only receive this error message and hibernating only works by using the command line, but not the GNOME menu anymore. Please see this small video clip for details:

https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/7988080/4302029f-6701-4bd8-8cf0-1428740d535a

Maybe this is related to this [upstream issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5421), which is reproducible for me?

Error message from the video:
```
Jun 07 21:11:49 [machine] gnome-shell[2274]: have hibernate true
Jun 07 21:11:56 [machine] gnome-shell[2274]: Object .Gjs_hibernate-status_dromi_confirmDialog_ConfirmDialog (0x55b50e3615e0), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jun 07 21:11:56 [machine] gnome-shell[2274]: == Stack trace for context 0x55b509284130 ==
Jun 07 21:11:56 [machine] gnome-shell[2274]: #0   55b50eab7ee8 i   /home/[username]/.local/share/gnome-shell/extensions/hibernate-status@dromi/confirmDialog.js:168 (38c894f6c240 @ 43)
Jun 07 21:11:56 [machine] gnome-shell[2274]: #1   55b50eab7e68 i   resource:///org/gnome/shell/ui/dialog.js:130 (9f0a32c5060 @ 11)
```

I tried reinstalling the extension, disabling all other extensions and rebooting the machine. GNOME 44 on Arch Linux is used here, sadly I'm not sure if this issue started after updating to 44. All other options from the same menu are working fine, only hibernating isn't working anymore.

**Comment by leggiero** [comment]
@theraser I have exactly the same behaviour on Gnome 44.2 (Fedora 38). Only the **Hibernate** button doesn't work and I have the same error in the log:
(note that the **Hibernate Sleep** works as expected)

```
Jul 10 13:36:07 laptop gnome-shell[2858]: have hibernate true
Jul 10 13:36:13 laptop gnome-shell[2858]: Object .Gjs_hibernate-status_dromi_confirmDialog_ConfirmDialog (0x562441c08a40), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jul 10 13:36:13 laptop gnome-shell[2858]: == Stack trace for context 0x5624416567d0 ==
Jul 10 13:36:13 laptop gnome-shell[2858]: #0   562442965738 i   /home/user/.local/share/gnome-shell/extensions/hibernate-status@dromi/confirmDialog.js:168 (32449e447470 @ 43)
Jul 10 13:36:13 laptop gnome-shell[2858]: #1   5624429656b8 i   resource:///org/gnome/shell/ui/dialog.js:130 (1680978c5060 @ 11)
```

**Comment by leggiero** [comment]
I was able to fix the issue in Gnome 44 with the pull request https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/103
