### ISSUE TITLE
Hibernation option appears only in the situation i can't use it (Secure boot)

### ISSUE THREAD

**Issue by Naim2000** [arelange/gnome-shell-extension-hibernate-status#102]
I have secure boot on right now. Every time i interact with the menu at the top right, this message appears in dmesg:
`Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7`

However, if I went to turn it off in the BIOS setup and head back to Ubuntu, the option disappears.
Video demonstration 

https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/44107089/ba4b4183-10bc-40bf-9ff9-f88ec6fd454a

https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/44107089/1349b6c3-2bd2-4297-837f-84fdc2044c44

**Comment by p91paul** [comment]
see if suggestions in our readme are helpful https://github.com/arelange/gnome-shell-extension-hibernate-status

**Comment by Naim2000** [comment]
Works nicely now, thank you
