### ISSUE TITLE
GNOME 45 support is not available in gnome extensions website.

### ISSUE THREAD

**Issue by FiestaLake** [arelange/gnome-shell-extension-hibernate-status#109]
While the repository itself contains support GNOME 45, the extension website hasn't been updated to reflect the changes.

**Comment by p91paul** [comment]
I am currently transferring the extension to @slaclau, we are awaiting someone from the gnome team to perform the transfer. Please wait or install manually from github.

**Comment by p91paul** [comment]
Since transferring was taking too long, I uploaded the new version to extensions.gnome.org, I hope it will be available in a few days.

**Comment by asfernandes** [comment]
Still not available for me.

**Comment by lobothiago** [comment]
I have installed 1.14-rc1 manually to GNOME 45 (Ubuntu 23.10) and I see the following error in the Extension Manager:

![image](https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/8550957/7a02400d-43ba-4fa0-a2be-2b971ad892c3)

Is this something you've seen?

**Comment by lobothiago** [comment]
> I have installed 1.14-rc1 manually to GNOME 45 (Ubuntu 23.10) and I see the following error in the Extension Manager:
> 
> ![image](https://user-images.githubusercontent.com/8550957/278833162-7a02400d-43ba-4fa0-a2be-2b971ad892c3.png)
> 
> Is this something you've seen?

I have just noticed that https://github.com/arelange/gnome-shell-extension-hibernate-status/issues/110 mentions the same issue I reported above.

**Comment by p91paul** [comment]
@slaclau extension was rejected because of those issues, can you look into them?

> 1. Please use a less generic name for the default class you are exporting (for stack trace).
>
> 2. Please remove `Mainloop` imports (line 6 extension.js) and use `GLib` instead.
> 
> 3. Timeout should be removed on disable (line 63 extension.js):
>     https://gjs.guide/extensions/review-guidelines/review-guidelines.html#remove-main-loop-sources
>     
>     Also remove the source id in disable for `idle_add()`s you are creating in extension.js.

See https://extensions.gnome.org/review/47017

**Comment by slaclau** [comment]
Thanks for sharing the review, I'll try to make these changes one day this week.
