### ISSUE TITLE
What does the new fourth button do?

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [arelange/gnome-shell-extension-hibernate-status#11]
The one with the twisted arrow.

**Comment by p91paul** [comment]
Hi, the button is not added by this extension but is present in Gnome Shell itself (you possibly updated recently?). It is a lock rotation button, and it's meant to be used on a tablet to prevent it from switching from portrait to landscape and vice-versa. It is usually disabled on computers, but sometimes autodetection fails. Here are more details and how to remove it! http://unix.stackexchange.com/questions/206479/what-is-the-icon-between-settings-and-lock-screen-in-gnome3
