### ISSUE TITLE
Doesn't work on Fedora 39

### ISSUE THREAD

**Issue by realKarthikNair** [arelange/gnome-shell-extension-hibernate-status#114]
- Extension installed from Github (since the one on extensions page still doesn't support Gnome 45 yet)
 - Menu buttons do show up ✅ 
 - Clicking on "Hibernate" button doesn't do anything ❌ 
 - Clicking on "Suspend then hibernate" only suspends the system
 - Clicking on "Hybrid Sleep" makes the screen go black and freezes until system is forcefully rebooted  
 - hibernation via `systemctl hibernate` works ✅ 

System info : 

```bash
karthik@fedora:~$ sudo inxi --swap -S && gnome-shell --version
System:
  Host: fedora Kernel: 6.5.10-300.fc39.x86_64 arch: x86_64 bits: 64
    Console: pty pts/2 Distro: Fedora release 39 (Thirty Nine)
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 0 KiB (0.0%) dev: /dev/zram0
  ID-2: swap-2 type: partition size: 20 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p6
GNOME Shell 45.1
```

![image](https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/78267371/c33a2374-db35-461e-97c4-e543d418f96b)

**Comment by slaclau** [comment]
Hi, sorry I've taken a while to look at this, would you be able to test some things / answer some questions?
- Does the Hibernate Dialogue open?
- Does it work if you disable the Hibernate Dialogue?
- Can you find the lines in journalctl showing the attempted hibernation?

**Comment by slaclau** [comment]
The output of this would be useful: `sudo journalctl -u systemd-hibernate.service`

**Comment by realKarthikNair** [comment]
@slaclau I no longer use the hibernation feature at all so can't help really sorry.
