### ISSUE TITLE
Add overview search actions

### ISSUE THREAD

**Issue by JosiahFu** [arelange/gnome-shell-extension-hibernate-status#115]
I tend to use the overview search to suspend/shutdown more often than the quick settings menu, so it would be nice to have the hibernate options there as well.

![Suspend action in overview search](https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/69983796/ee906c96-f2a6-49c7-a1fa-0ed9d29c2cde)

![No hibernate action in overview search](https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/69983796/3819a25d-0f2d-4f07-8ccf-66f13cbee078)

**Comment by ViBE-HU** [comment]
this would be great. like shutdown, restart, logout.

**Comment by slaclau** [comment]
This is out of scope of the extension but can be achieved easily by adding files like this to /usr/share/applications or ~/.local/share/applications
```
[Desktop Entry]
Type=Application
Name=hibernate
Icon=application-exit-symbolic
Exec=systemctl hibernate
```

**Comment by julienfalque** [comment]
I think the extension can be relevant for implementing this feature for two reasons:
* it would integrate with the confirm dialog option;
* the action would be available only if hibernation is actually enabled on the system.

Would you consider reopening this issue?

**Comment by JosiahFu** [comment]
My current workaround for the confirm dialog is
```
Exec=bash -c 'zenity --question --title "Hibernate" --text "Do you really want to hibernate the system?" --icon "dialog-error-symbolic" --ok-label "Hibernate" --cancel-label "Cancel" --default-cancel && systemctl hibernate'
```

**Comment by julienfalque** [comment]
Nice workaround. This feels a bit hacky though, and it needs to be implemented on every system where this is wanted.

**Comment by slaclau** [comment]
> I think the extension can be relevant for implementing this feature for two reasons:
> 
> * it would integrate with the confirm dialog option;
> * the action would be available only if hibernation is actually enabled on the system.
> 
> Would you consider reopening this issue?

You’ve made a good case for it, I guess we just need to implement a search provider - feel free to have a go: https://gjs.guide/extensions/topics/search-provider.html

I can have a try when I get a bit of time
