### ISSUE TITLE
Hibernation button does not show up, but systemctl hibernate works

### ISSUE THREAD

**Issue by yasmah74** [arelange/gnome-shell-extension-hibernate-status#116]
I wrote the Text below to `/etc/polkit-1/localauthority/10-vendor.d/com.ubuntu.desktop.pkla` but the button still dont appers in the menu. I have this Problem since i upgraded my Ubuntu to 23.10. There was not a Problem before in 23.04. The Command `systemctl hibernate` works of course.

Does anyone have the same Problem in Ubuntu 23.10?

[Enable hibernate in upower]
Identity=unix-user:*
Action=org.freedesktop.upower.hibernate
ResultActive=yes

[Enable hibernate in logind]
Identity=unix-user:*
Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.handle-hibernate-key;org.freedesktop.login1;org.freedesktop.login1.hibernate-multiple-sessions;org.freedesktop.login1.hibernate-ignore-inhibit
ResultActive=yes

**Comment by montefra** [comment]
On my Ubuntu 23.10 the buttons show up after installing `polkitd-pkla`

    sudo apt install polkitd-pkla

source: one of the review here: https://extensions.gnome.org/extension/755/hibernate-status-button/

**Comment by yasmah74** [comment]
> On my Ubuntu 23.10 the buttons show up after installing `polkitd-pkla`
> 
> ```
> sudo apt install polkitd-pkla
> ```
> 
> source: one of the review here: https://extensions.gnome.org/extension/755/hibernate-status-button/

Thanks! Problem solved
