### ISSUE TITLE
Option to ignore different mode

### ISSUE THREAD

**Issue by camlafit** [arelange/gnome-shell-extension-hibernate-status#117]
Hello

When we enable hybrid mode, both hibernation mode are proposed. 
Could be interesting to disable "à la demande"  these options, in my case I would get only hybrid mode enabled. And disable hibernation and suspend modes.

Is it possible to provided an options as this ?

Thanks a lot

**Comment by slaclau** [comment]
I believe this is covered by the existing settings, can you confirm that you have tested these please?

**Comment by slaclau** [comment]
I have made some updates to allow suspend, restart, and power off to be hidden as well, can you try with the latest master branch to see if it works for you?
