### ISSUE TITLE
Update in GNOME extensions index

### ISSUE THREAD

**Issue by almereyda** [arelange/gnome-shell-extension-hibernate-status#12]
Chromium with GNOME Shell integration shows me https://extensions.gnome.org/extension/755/hibernate-status-button/ as outdated:

![bildschirmfoto von 2016-11-09 00-13-28](https://cloud.githubusercontent.com/assets/1645308/20121384/64fe7244-a611-11e6-9e04-3e0519abe02b.png)

This could also help answering to the comments below, as GNOME 3.20 is supported the latest since April in the git tree, but apparently not in the extensions catalogue.

Mentioning the currently uploaded version and supported GNOME versions in the description text would be helpful, too.

**Comment by p91paul** [comment]
It also shows a green update button :) the outdated status is related to the extension you have installed, not to the one available on the site; if you update it, it will no longer appear as outdated!

The comments refer to the fact that fedora disables hibernation by default, unless the user configures their system to allow it there is nothing this extension can do.
