### ISSUE TITLE
Extension is doing suspend instead of hibernate in debian trixie/sid

### ISSUE THREAD

**Issue by ulefr01** [arelange/gnome-shell-extension-hibernate-status#121]
On debian 12 trixie/sid :
'sudo systemctl hibernate'  works correctly and is doing the hibernate.
this gnome extension is doing a 'suspend' instead of hibernate.

**Comment by ulefr01** [comment]
Any update on this issue ?

**Comment by slaclau** [comment]
Can you include a copy of `sudo journalctl -u systemd-hibernate.service` and `sudo journalctl -u systemd-suspend.service` please

**Comment by ulefr01** [comment]
please note i have an alias : 
alias hibernate 'sudo systemctl hibernate'

[20241111_output.txt](https://github.com/user-attachments/files/17706302/20241111_output.txt)

**Comment by ulefr01** [comment]
sorry reopened now

**Comment by ulefr01** [comment]
If i use /etc/systemd/sleep.conf see attached file 
systemctl daemon-reload
and select button = 'Suspend then hibernate'
then it works.
[sleep.conf.txt](https://github.com/user-attachments/files/17707486/sleep.conf.txt)

**Comment by slaclau** [comment]
Great
