### ISSUE TITLE
Enable hybrid and suspend-then-hibernate as automatic option.

### ISSUE THREAD

**Issue by hansbogert** [arelange/gnome-shell-extension-hibernate-status#125]
I've got the pluging working fine, but it would be awesome if it would also have the options for hybrid sleep and suspend-then-hibernate as option to the automatic suspend here:

![image](https://github.com/user-attachments/assets/74c4bf2e-e638-418b-82e7-1207ce915d48)

Same for lid close of a laptop.

Is that feasible with an extension in gnome?

**Comment by slaclau** [comment]
These gsettings options might help you here - but I think it’s out of scope of the extension. Happy to reconsider if lots of people disagree.

https://wiki.archlinux.org/title/GNOME#Power
