### ISSUE TITLE
GNOME 47 Support

### ISSUE THREAD

**Issue by Toorero** [arelange/gnome-shell-extension-hibernate-status#127]
Is it possible to get GNOME 47 Support?

**Comment by Toorero** [comment]
For me there are no breaking changes preventing just altering the defined shell versions https://github.com/arelange/gnome-shell-extension-hibernate-status/blob/4b2002751e2bbcd839d8411d53206d7b0376c06e/metadata.json#L6

**Comment by mipimipi** [comment]
GNOME 47 support would indeed by great.

**Comment by slaclau** [comment]
I've merged the PR and uploaded a new version to gnome extensions
