### ISSUE TITLE
Button not showing in Ubuntu 16.10 and above

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [arelange/gnome-shell-extension-hibernate-status#14]
I have installed the extension but no button shows up in the menu.

Going through `lg` the extension emitted no errors.

**Comment by RicardoEPRodrigues** [comment]
After running `journalctl` I found that the extension is throwing some errors:

    JS ERROR: TypeError: childToShow is null
    AltSwitcher<._sync@resource:///org/gnome/shell/ui/status/system.js:84:13
    wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
    Extension<._updateHibernate@/home/ricardo/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:111:64
    wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
    Extension<._updateHaveHibernate/<@/home/ricardo/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:106:13
    Extension<._loginManagerCanHibernate/<@/home/ricardo/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:38:25

**Comment by p91paul** [comment]
sorry, I had a difficult May. Ubuntu 16.10 should have gnome-shell 3.20, which is strange since I used this extension successfully on 3.20. Have you installed a later version (3.24) from some external repository by any chance?

**Comment by RicardoEPRodrigues** [comment]
I'm currently using Ubuntu GNOME 17.04 that ships with shell 3.24, but the button didn't show up in 3.20 either.

**Comment by c7hm4r** [comment]
I could enable to show the hibernation button in Ubuntu 17.10 following the [official documentation](https://help.ubuntu.com/stable/ubuntu-help/power-hibernate.html). However, I could not get the resuming to work, which is rather a problem with Ubuntu or my hardware than with this extension. In Fedora it all works ;)

**Comment by p91paul** [comment]
Looking at the error after @c7hm4r comment, it makes sense: if hibernation is disabled in login manager, the button won't show up (and print that error on the system log).
If this issue persists after following the documentation linked above, I will reopen this.
