### ISSUE TITLE
Dazed and confused, but trying to continue (bad hibernation function)

### ISSUE THREAD

**Issue by ItayXD** [arelange/gnome-shell-extension-hibernate-status#16]
when i use the button my computer goes to a different (and undesirable) state than when running
`systemctl hibernate` from the terminal.
I tried to understand whats going on in the code by couldn't really...
Anyway when I use the button I get the following error:
```
NMI received for unknown reason
Do you have a strange power saving mode enabled?
Dazed and confused, but trying to continue 
```
I kind of goes in to hibernate state and when waking up in to a suspend state.
Should probably be easy to fix as I is just the final call that makes the mess

**Comment by p91paul** [comment]
Could you please try replacing your ~/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js file with this one: 
[extension.zip](https://github.com/arelange/gnome-shell-extension-hibernate-status/files/1528875/extension.zip)

Then restart your shell (alt-f2, r, enter) and retry. I've tried replacing the whole call to logind with a sympler "open a shell and launch systemctl hibernate" equivalent, let's see if it works on your system.

**Comment by ItayXD** [comment]
Hi,
Sorry I updated the kernel from 4.14 to 4.15 and it works now..
