### ISSUE TITLE
No feedback when hibernate is not supported because of SecureBoot

### ISSUE THREAD

**Issue by wagner-certat** [arelange/gnome-shell-extension-hibernate-status#17]
When clicking on the button, it ask me if I really want to hibernate, but after clicking yes, nothing happens. Same for the hybrid sleep.

There is not output in the journal.

**Comment by wagner-certat** [comment]
EDIT: In my case Secure Boot prevented hibernation. A error message would be nice.

See e.g. https://askubuntu.com/questions/868208/how-to-activate-hibernation-in-16-04-1-systemd for explanation and how to detect it (`/sys/power/disk`).

**Comment by p91paul** [comment]
Now we have a 20 seconds timer. If after 20 seconds the timer is actually called, it means hibernation failed and a dialog presenting the problem is shown to the user.
