### ISSUE TITLE
Remove confirmation dialog or make it configurable

### ISSUE THREAD

**Issue by PhrozenByte** [arelange/gnome-shell-extension-hibernate-status#2]
Hibernation is no harmful action, so you shouldn't ask for confirmation at all. In general, it's best practise to ask for confirmation only when performing actions which can't be undone. If you stand on a confirmation dialog, a config option would be just great.

**Comment by arelange** [comment]
Confirmation was added because someone complained about it. He hibernated his system during an update and broke it up. It is rare but it is harmful in this case.

**Comment by PhrozenByte** [comment]
You shouldn't make this decision based on a broken system, everything you do on your computer could be harmful if the system is broken - e.g. opening any application could result in a kernel panic. Furthermore a confirmation dialog doesn't help a user in this situation - he doesn't know when this rare situation arises, so how could he do anything different? Anway, as said, if you stand on a confirmation dialog, a config option would be just great.

**Comment by arelange** [comment]
According to this user, the system was not broken before the hibernation, only after (I guess hibernation during kernel update is not so cool). It also happened to me a couple of times to launch an update and hibernate before it has ended (fortunately without crashes), and the 1s confirmation to think about it was useful for me.
NOTE: the prurpose of this comment is not to blame the (great) idea of a config option, but is giving more information for the vonunteer who will improve the extension, and let him chose how to improve it (option ? "never confirm again" checkbox ? timeout ? confirmation removal in exchange of system update checking ? anything else ?). I would be glad to pull anything better.
