### ISSUE TITLE
From suspend into hibernation?

### ISSUE THREAD

**Issue by orschiro** [arelange/gnome-shell-extension-hibernate-status#20]
Dear @arelange,

Please apologise as this is clearly out of scope of this extension. 

However, my question is related and I am seeking your advice. 

When I close my laptop lid, my laptop turns into suspend (still draining battery). 

I am wondering if GNOME has a feature that can send my laptop from this state of suspend into hibernation (no draining of battery) after X minutes or if a certain critical battery level has been reached.

Are you aware of such a feature?

Thank you!

**Comment by p91paul** [comment]
According to [this](https://wiki.archlinux.org/index.php/Power_management#Suspend_and_hibernate) systemctl has a `suspend-then-hibernate` command.

For a more complicated solution check this: https://superuser.com/questions/298672/linuxhow-to-hibernate-after-a-period-of-sleep

Never actually tried so I don't know if any of this works!

**Comment by orschiro** [comment]
Thank you, @p91paul!

This command will ship with Fedora 29. I will wait until then and try it out. :-)
