### ISSUE TITLE
The second URL in the FAQ in the README.md is dead

### ISSUE THREAD

**Issue by janvlug** [arelange/gnome-shell-extension-hibernate-status#21]
I found this working URL that looks similar, though for an older Ubuntu version:
https://help.ubuntu.com/16.04/ubuntu-help/power-hibernate.html

**Comment by p91paul** [comment]
That's unfortunate....16.04 is quite old. Anyway I added your link, I hope information on askubuntu on the first link is more relevant for newer versions.

It's sad to see ubuntu has basically given up in supporting hibernation, even removing its help pages about it.

Thanks for bug report!
