### ISSUE TITLE
Internationalisation support?

### ISSUE THREAD

**Issue by orschiro** [arelange/gnome-shell-extension-hibernate-status#22]
Dear @arelange,

Does your extension support internationalisation, i.e. can I help translate the dialog windows into different languages?

Thank you!

Yours, 

Robert

**Comment by p91paul** [comment]
No, that is not implemented yet. Are you able to help with this (extract strings and put them in .po/.mo files)?

**Comment by orschiro** [comment]
Dear Paolo,

I am sorry but my schedule for the next weeks has changed and I won't be
able to dedicate time to this task.

I suggest we close it until someone else can jump in who is able to help
out?

Yours,

Robert

**Comment by p91paul** [comment]
No need to close this, it's good this is publicly tracked as "todo".

**Comment by orschiro** [comment]
OK, hope someone else can jump in! :-)

Thanks again for your nice extension.

Yours,

Robert

**Comment by p91paul** [comment]
Internationalization support was implemented with https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/40
I then added italian translation, and I welcome contributions for other languages.
