### ISSUE TITLE
Doesn't work with Gnome 3.32 Antergos/Arch

### ISSUE THREAD

**Issue by Taylor-Schmidt-NDSU** [arelange/gnome-shell-extension-hibernate-status#25]
Was working very well until I updated to Gnome 3.32. The button is still there, and alt-click will perform the hybrid sleep. However, when clicking the hibernate button regularly, nothing happens. The dialog box does not even pop up

**Comment by frol** [comment]
Same problem here with my 2 laptops (also Arch and Gnome 3.32)

**Comment by Miladdarren** [comment]
Same here on Manjaro Gnome 3.32

**Comment by lakotamm** [comment]
Gonna join the group... running Ubuntu 19.04

**Comment by davidbailey00** [comment]
I've updated the extension to GNOME 3.32; hopefully should be approved soon!

https://extensions.gnome.org/extension/1780/hibernate-status-button/
https://github.com/davidbailey00/gnome-shell-extension-hibernate-status

**Comment by p91paul** [comment]
@davidbailey00 why create a new repository & extension on e.g.o.? please contact me (you can find my email in commits, anyway it's my github username @gmail.com), we can discuss giving you commit auth on this repo and transferring ownership of the current extension on e.g.o., it's a shame to duplicate effort! I'd be very happy to leave my role as maintainer to someone willing to...

**Comment by p91paul** [comment]
also, can you open a pull request to have your fixes merged?

**Comment by davidbailey00** [comment]
Hey @p91paul! I created a new repo and extension since it looked like this one was dead, for the following reasons:

- No collaborator response to this issue for over 30 days
- No response to PR #24 for over 30 days
- The README on the latest branch said:
  > Unfortunatly, the original developper do not really use it anymore. Since many people were waiting it to be updated, it would be a good thing if someone else could maintain it !

However, now that I know this repo is still active I'd be happy to submit a PR and collaborate on efforts to maintain the extension :)

**Comment by davidbailey00** [comment]
Fixed in #26
