### ISSUE TITLE
Stopped working after gnome update to 3.28.2

### ISSUE THREAD

**Issue by ksonbol** [arelange/gnome-shell-extension-hibernate-status#31]
The extension was working without any problems on Ubuntu 18.04 until recently it stopped working. I am doubting the latest Gnome update has caused this but I am not sure. Hibernate still works with 
`sudo systenctl hibernate`

Gnome version: 3.28.2
Ubuntu version: 18.04.2 LTS

**Comment by p91paul** [comment]
Looks like a duplicate of #30. Let's continue there.
