### ISSUE TITLE
Undefined action menu

### ISSUE THREAD

**Issue by mokilcde** [arelange/gnome-shell-extension-hibernate-status#33]
Hi!

I got the following message after updating to Gnome Shell version 3.33.90:
gnome-shell[2532]: JS WARNING: [/srv/home/michael/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js 187]: reference to undefined property "_actionsItem"
gnome-shell[2532]: Extension "hibernate-status@dromi" had error: TypeError: this.systemMenu._actionsItem is undefined

CU
  Michael

**Comment by p91paul** [comment]
@davidbailey00 please confirm you are going to take care of this, since you are the maintainer on e.g.o...

**Comment by p91paul** [comment]
duplicate of #34, which is now fixed in master.
