### ISSUE TITLE
Upload new version to extensions.gnome.org

### ISSUE THREAD

**Issue by p91paul** [arelange/gnome-shell-extension-hibernate-status#38]
Branch master is now 3.34 compatible.

**Comment by DanMan** [comment]
Doesn't work here on Fedora with Gnome 3.34.1. I get "Error" on extensions.gnome.org where the switch is after enabling it.

**Comment by p91paul** [comment]
Please make sure you downloaded v16, which was accepted on Sunday night.

**Comment by p91paul** [comment]
@DanMan that's strange. Can you please send error log? there is at least a review confirming it now works.

**Comment by 3mb3dw0rk5** [comment]
After update from gnome extensions webpage I still had the "Error" message, but running
`alt+f2 - r - enter` solved the problem. Maybe it also helps you @DanMan

**Comment by DanMan** [comment]
Sorry for my ignorance. I forgot I posted here.

Whichever version is now online works for me. Given what @3mb3dw0rk5 wrote, maybe it needed a reboot.

**Comment by p91paul** [comment]
Thanks, closing this.
