### ISSUE TITLE
Stopped working on Ubuntu after latest extension's upgrade

### ISSUE THREAD

**Issue by federicoon** [arelange/gnome-shell-extension-hibernate-status#39]
The extension has been working flawlessly on Ubuntu 19.04, until upgrade to latest version.
Since then, the hibernate icon has disappeared and on the "Installed Extensions" dashboard an "ERROR" button is displayed besides this entry.
I also tried to unistall and then reinstall the extension, but the error persists.

gnome-shell-extensions version: 3.32.0-1

This comes from journalctl:

```
nov 13 17:56:04 Home gnome-shell[2205]: Extension "hibernate-status@dromi" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)
nov 13 17:56:04 Home gnome-software[3066]: State change on user/*/*/shell-extension/hibernate-status_dromi/* from available to installed is not OK
nov 13 17:56:04 Home gnome-software[3066]: hibernate-status_dromi has error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)

```

**Comment by p91paul** [comment]
Please revert to v15. I have uploaded v17, which declares compatibility with 3.34 only, and reverted 3.32 to v15 by disabling v16.

**Comment by federicoon** [comment]
How can I revert to v15? The slider automatically installs the latest version

**Comment by p91paul** [comment]
if you are on gs 3.32 and you remove and reinstall, it should install the latest compatible with 3.32, which is v15 ATM.
