### ISSUE TITLE
GNOME 3.16 support?

### ISSUE THREAD

**Issue by DoctorJellyface** [arelange/gnome-shell-extension-hibernate-status#4]
[axel.sommerfeldt](https://extensions.gnome.org/accounts/profile/axel.sommerfeldt) says that it works fine on GNOME 3.16 after `3.16` was added to `metadata.json`. Please update it, I kinda need it. Thanks.

**Comment by Pepan** [comment]
I vote for this.

**Comment by mattymaloney** [comment]
The extension did not work for me (no hibernation button appears next to the power button) in Fedora 22 / gnome-shell 3.16.2. On another box, Fedora 21 / gnome-shell 3.14.4, it works perfectly.

I tried adding both 3.16 and 3.16.2 to the shell-versions in metadata.json, but the extension still did not work on that box. I haven't investigated any further.

**Comment by betseg** [comment]
Still nothing?

**Comment by arelange** [comment]
Oops, I never realized that someone was really interested in the work I published. As a result:
- I never checked my Github notifications
- I never saw someone requested it to be updated
- I never saw someone already did the job to update and requested to pull the modification
- I push my own modifications directly from my local computer ignoring this activity...
I sincerly apology for this really unpolite behavior !
The 3.16 patch has been commited and uploaded on Gnome website.
Thanks everyone for your support !
