### ISSUE TITLE
Install from command line

### ISSUE THREAD

**Issue by meaz** [arelange/gnome-shell-extension-hibernate-status#43]
Hi,
how can we install and enable this extension from command line?
I'm trying to install it with ansible.
Thanks  a lot

**Comment by p91paul** [comment]
you have to put files into .local/share/gnome-shell/extensions/<extension id as written in metadata.json>/
Then restart gnome shell to load the extension, and use gsettings to enable it. This procedure works in general for all extensions.

**Comment by meaz** [comment]
thanks @p91paul I did try that, but it still doesn't work. 
I did `git clone https://github.com/arelange/gnome-shell-extension-hibernate-status.git hibernate-status@dromi22`
It works if I user firefox gnome extension to install it. But with git clone, I get a get a orange triangle with a question mark in gnome extensions list.
I use debian buster and have gnome-shell 3.30.2.

**Comment by p91paul** [comment]
You also need to run:
glib-compile-schemas schemas/
in the extension's folder

**Comment by meaz** [comment]
> it's hibernate-status@dromi, not dromi22. Not sure if you just copied it wrong here.

yes I just copied it wrong



> You also need to run:
> glib-compile-schemas schemas/
> in the extension's folder

So, here is exactly what I did:
``
git clone https://github.com/arelange/gnome-shell-extension-hibernate-status.git hibernate-status@dromi
``
``
cd .local/share/gnome-shell/extensions/hibernate-status@dromi
``
``
glib-compile-schemas schemas/
``
I add hibernate-status@dromi in the enabled plugins in dconf
I even reboot: I still have the orange triangle with a question mark in gnome extensions list.

**Comment by p91paul** [comment]
can you post journalctl log? probably some error occurred

**Comment by p91paul** [comment]
what's your gnome-shell version?

**Comment by meaz** [comment]
First of all, thanks for your time and help @p91paul !

gnome-shell version is 3.30.2

`journalctl | grep hibernate`

gives me that error:
`
gnome-shell[2820]: Extension "hibernate-status@dromi" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)`

**Comment by p91paul** [comment]
I see. Latest master does not support gnome shell 3.30, unfortunately, try checking out commit 3c81d57fbc6c59a02067c7508abdca51a8688734

**Comment by p91paul** [comment]
Also, I have to warn you: gnome is making big changes to the shutdown menu in 3.36.
Most certainly this extension is not going to work, and will require a full rewrite. I hope that either gnome will include a hibernate option in its default menu, or someone is going to create another extension, but this one is likely to die.

**Comment by meaz** [comment]
Thanks a lot @p91paul ! I'm closing the ticket then.
Too bad this extension won't work anymore!
