### ISSUE TITLE
Stopped working after gnome update to 3.36

### ISSUE THREAD

**Issue by manhtukhang** [arelange/gnome-shell-extension-hibernate-status#44]
## System details:
- OS: `Archlinux`
- Kernel: `5.5.8-arch1-1`
- Gnome shell version: `3.36.0`

## Error logs:
```js
JS ERROR: Extension hibernate-status@dromi: TypeError:
this.systemMenu._createActionButton is not a function
enable@/home/tukm/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:180:49
enable@/home/tukm/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:242:15
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**Comment by p91paul** [comment]
gnome 3.36 made huge modifications to the shutdown overall user experience. I do not plan to fix this extension, I expect it to require a full rewrite and I don't have neither the time nor motivation (basically, I stopped hibernating a few years ago due to a shift in how I use my personal laptop).

I will however accept pull requests, even if they break older releases.

**Comment by allentiak** [comment]
@p91paul
It's a pity you don't have the time to maintain this extension anymore. Thanks for your hard work on this!

Maybe you could state the unmaintained status in the README? Maybe that could help finding a new maintainer...

**Comment by p91paul** [comment]
Done, thanks for your suggestion @allentiak

**Comment by p91paul** [comment]
Many thanks to @tonyzhc for his contribution, the extension is now 3.36 compatible. I've uploaded to extensions.gnome.org and is now pending review

**Comment by allentiak** [comment]
> Done, thanks for your suggestion @allentiak

You're welcome, @p91paul! Glad I was able to help.

**Comment by allentiak** [comment]
> I've uploaded to extensions.gnome.org and is now pending review

Great, @p91paul !

Do you have an idea of how long this usually takes?

**Comment by p91paul** [comment]
some days usually
