### ISSUE TITLE
Stopped working after upgraded OS to Fedora 32

### ISSUE THREAD

**Issue by benneteapen** [arelange/gnome-shell-extension-hibernate-status#46]
After I upgraded to Fedora 32, I get this error :

> The settings of extension hibernate-status@dromi had an error:
> ```
> Error: Expected type object for Argument 'widget' but got type 'undefined'
> ```
> 
> Stack trace:
> ```
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> start@resource:///org/gnome/gjs/modules/script/package.js:206:5
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
> 

```
[beapen@home-fedora ~]$ gnome-shell --version
GNOME Shell 3.36.1
```

**Comment by benneteapen** [comment]
Just figured it doesn't work for Gnome 3.36 https://github.com/arelange/gnome-shell-extension-hibernate-status#gnome-shell-336
That's a bummer.

**Comment by p91paul** [comment]
Thanks to a pull request, this should be solved in master. I've uploaded to extensions.gnome.org and is pending review
