### ISSUE TITLE
Preferences Dialog accessible but not available

### ISSUE THREAD

**Issue by mestrode** [arelange/gnome-shell-extension-hibernate-status#53]
In gnome-shell the preferences dialog is accessible, but will just show an error:
The button should be made invisible or a small configuration dialog created.

![Screenshot from 2020-05-23 18-12-40](https://user-images.githubusercontent.com/35630715/82735338-41b3b780-9d21-11ea-86c8-9c4803c21201.png)

**Comment by elpraga** [comment]
I am experiencing the same error. After clicking at **Technical Details** I get:

```
Error: Expected type object for Argument 'widget' but got type 'undefined'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by p91paul** [comment]
The preferences dialog is not implemented and we don't really have useful options to set there. Would need some looking into to hide the button or avoid the error message.

**Comment by quazardous** [comment]
hi, maybe you could add some toggle to choose the available actions (hybrid, etc). and display the used command.
