### ISSUE TITLE
Hibernate option does not initiate system shutdown. Manual shutdown is required. Afterwhich system fails to boot.

### ISSUE THREAD

**Issue by paulwin1** [arelange/gnome-shell-extension-hibernate-status#58]
The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
I tried hibernating on my Manjaro Mikah Gnome edition(3.36) with Swap partition for hibernation.
The system will go black and unresponsive but does not fully shut down(power button indicator LED is on) and cannot reboot via hitting the power button.
Manual shutdown via holding down the power button turns the machine off but turning it back on, the system refuses to boot and stays at the boot screen logo.
Second time booting success and can boot from the system.

**Comment by p91paul** [comment]
the preferences page is not implemented.
Does hibernation via `systemctl hibernate` work?

**Comment by paulwin1** [comment]
> the preferences page is not implemented.
> Does hibernation via `systemctl hibernate` work?

Yes. systemctl hibernate partially works. The systems shuts off but I can't get it to boot the next time. I have to completely shut it off manually by holding the power button.

**Comment by p91paul** [comment]
This means your issues are indipendent from this extension, it might be something with your system or drivers. Try getting help through manjaro wiki or forums, once systemctl hibernate fully works this extension should too!
