### ISSUE TITLE
Error when update new Version 

### ISSUE THREAD

**Issue by robindanzinger** [arelange/gnome-shell-extension-hibernate-status#59]
see comments in https://extensions.gnome.org/extension/755/hibernate-status-button/

It worked in previous version. But when updating or reinstalling new version, error occurs.
Using: Ubuntu 20.04.1 LTS

The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by p91paul** [comment]
What doesn't work exactly? the preferences page was never implemented. 
You don't see the hibernate button in the menu?
Which gnome-shell version are you on?

**Comment by robindanzinger** [comment]
gnome-shell 3.36.
When installing the extension from https://extensions.gnome.org/extension/755/hibernate-status-button/ it will not be installed correctly. 
Actual:
![image](https://user-images.githubusercontent.com/3295716/95683383-228fc680-0beb-11eb-8e76-6c3fa3b954ac.png)

Expected:
![image](https://user-images.githubusercontent.com/3295716/95683405-4c48ed80-0beb-11eb-9b08-7c2d94a8ac61.png)
 
In the menu there is no hibernate button. With previous version, it worked.

**Comment by p91paul** [comment]
Please try uninstalling and reinstalling.
During reinstall, if the "ERROR" appears again, please collect logs. Do not click on the preferences button.

**Comment by robindanzinger** [comment]
I reinstalled it again. Now it works. The Hibernate button appears in the menu. Great work!
Thank you very much.

**Comment by csylvain** [comment]
i reinstalled minutes ago and no improvement. never even opened the preferences.


![Hibernate-Extension-screenshot](https://user-images.githubusercontent.com/6507573/95787489-272aac80-0cc9-11eb-83cd-ee4003025d8f.png)
