### ISSUE TITLE
Insufficient Swap

### ISSUE THREAD

**Issue by TZanke** [arelange/gnome-shell-extension-hibernate-status#62]
My Suse system only had 8GB of Swap available, but 16GB system memory installed. Randomly the system had not bootet up, just got a black screen after hibernation.

Would be nice if your extension could check swap before entering hibernation. I dont know why linux does this check not by itself.

**Comment by p91paul** [comment]
Indeed I would expect linux to do this check, however I'm not sure about 16 RAM = 16 GB of swap required to hibernate. AFAIK hibernation is smart enough not to save free space, and compression might be applied as well. So if I implement such a check, it might prevent hibernation when it's perfectly feasible.

**Comment by TZanke** [comment]
ok i know what you are talking about. I googled a little bit and found a recommendation for hibernation saying 1.5x of RAM. So 24GB SWAP are recommended on my 16GB system to use hibernation. But i think this should be the choice of the owner. Maybe it would be useful to show the current setting (8GB Swap / 16RAM) on the hibernation confirmation dialog. This had helped me a lot to find the problem.

Thanks for your reply. If you like, feel free to close the ticket.
