### ISSUE TITLE
can't understand the problem !!

### ISSUE THREAD

**Issue by ponuji2404** [arelange/gnome-shell-extension-hibernate-status#63]
Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

please help.

**Comment by p91paul** [comment]
the issue is fixed for gnome-shell 3.38.
For lower versions, if it happens during upgrade just restart your system or uninstall then reinstall.
Do not open extension preferences as they are not implemented.
