### ISSUE TITLE
reporting error - Expected type object for Argument 'widget' but got type 'undefined'

### ISSUE THREAD

**Issue by csylvain** [arelange/gnome-shell-extension-hibernate-status#65]
status button not working. Ubuntu 20.04.2 LTS and Gnome snaps 3-28-1804/145 3-34-1804/66

error message:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by p91paul** [comment]
sorry, which gnome version are you on?
This should be fixed by the latest version I uploaded for Gnome 3.36, 3.38 and 40.

**Comment by p91paul** [comment]
Also, you should be able to fix it by uninstalling and reinstalling.

**Comment by csylvain** [comment]
i expect the one i am "on" is the latest of the two versions i reported
(Ubuntu 20.04.02 LTS), and the earlier gnome version is simply the
compatibility libraries.

**Comment by csylvain** [comment]
i am not certain why, but i appear to have resolved the issue not by using
(gnome) Tweaks, but instead use my browser (firefox in this case) at
extensions.gnome.org and poke at the extension configuration button.
immediate result was red "Error" indication. rebooting the system cleared
that indication.

**Comment by p91paul** [comment]
if you are on 3.34 then sure, the error appears if you try and open preferences. That's because the preferences widget was not implemented (there are no preferences to be set).

Not sure why you're installing an older version from snap, since Ubuntu 20.04 ships with 3.36 by default.

Anyway since it seems like the extension now works for you, I'm going to close this issue.

**Comment by csylvain** [comment]
i have not selected any gnome version or snap not automatically offered and
installed by the distro

**Comment by csylvain** [comment]
also: preferences widget appeared before and again after the aforementioned
error condition.
