### ISSUE TITLE
Find a new maintainer

### ISSUE THREAD

**Issue by arelange** [arelange/gnome-shell-extension-hibernate-status#7]
Hi !

I made this Gnome extension for my personal use but I do notre really use anymore. Since I realized many people were waiting it to be updated, I think it would be a good thing if someone else can maintain it (and make it avalaible more quickly for 3.18 !)

Apply now !

**Comment by DoctorJellyface** [comment]
Just make a `README-md` file with this, you find someone quicker. Also, in 3.16 I experienced a little bug where the bug button was off-centered.

**Comment by arelange** [comment]
thanks for the advice, README.md created

**Comment by p91paul** [comment]
Hi! I just ported this extension to 3.20 (just metadata.json editing is needed). I would gladly help maintaing this extension, including upload to extensions.gnome.org, if you still need help with it. If you are interested, please email me at p91paul at gmail dot com!

**Comment by arelange** [comment]
As a confirmation for official Gnome Shell reviewers, you have my blessing to give all the rights of this extension on gnome website to @p91paul !

**Comment by arelange** [comment]
And now that @p91paul owns the rights on extensions.gnome.org, he is officially the new maintainer of this extension ! Congratulations !

**Comment by p91paul** [comment]
Thanks @arelange!
