### ISSUE TITLE
[Feature Request] hybrid sleep optional

### ISSUE THREAD

**Issue by benintech** [arelange/gnome-shell-extension-hibernate-status#78]
Please add an option to disable the Hybrid Sleep entry

**Comment by 40417256** [comment]
Please remove this option, there is nothing such as hybrid sleep in Linux, or make it configurable (option to remove the menu item). 

Thank you

**Comment by 40417256** [comment]
Ok, for those who want do do it manually, edit extension.js line 91, comment out and paste line 89

to become:

/*                        asyncCallback(result[0] != 'no');*/
                          asyncCallback(false);

Menu entry in not present anymore.

Have a better day, and thanks to the author for this nice extension.

**Comment by jibsaramnim** [comment]
I dabbled with this a bit, I need to clean up what I made a bit but I'm happy to provide a PR if there's interest in this @p91paul?

**Comment by p91paul** [comment]
I would gladly accept a PR for this, thanks!
