### ISSUE TITLE
Native Host-Connector not found

### ISSUE THREAD

**Issue by GLehnhoff** [arelange/gnome-shell-extension-hibernate-status#83]
systemctl hybernate works fine, but not the integration to Gnome. https://extensions.gnome.org/extension/755/hibernate-status-button/ manged to install the extension to Firefox and Chromium; however, there is a message that the native host-connector is not found. Any idea what to do in order to have a Gnome menu entry?

**Comment by p91paul** [comment]
Can you post a screenshot of the error message?

**Comment by GLehnhoff** [comment]
Sure, here we are; however in German language:
![Bildschirmfoto vom 2022-10-18 12-04-38](https://user-images.githubusercontent.com/5453201/196403008-c15b2e84-cae5-4881-8a56-62cc5fba3bf2.png)
BTW: Other than said in the screenshot, the documentation does not help. However, I have seen entries in forums, that the problem is, that Firefox as well as Chromium are Snap packages and I should look for native packages, which I have done but I did not find a possibility to install the browsers other than Snap.

**Comment by GabrielMalta** [comment]
Try installing extensions through this tool
`sudo apt install gnome-shell-extension-manager`

**Comment by p91paul** [comment]
Closing this since it's likely ubuntu-specific and not related to this extension. You might be able to get further help on your distributions forums/Q&A sites!
