### ISSUE TITLE
Missing translations for the term "Hybrid Sleep"

### ISSUE THREAD

**Issue by saulotoledo** [arelange/gnome-shell-extension-hibernate-status#86]
The term "Hybrid Sleep" is missing from a few translation files.
I created a PR for a few of them at https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/85.
However, the languages below still miss the translation of the term, but I do not know those languages. I am adding the names of the previous contributors to those languages below. Maybe they can help with that.

- Czech (@pervoj)
- Polish (@tebaranowski)
- Persian (@mskf1383)
- Nederlands (@Vistaus)
- Occitan (@ensag-dev)
- Simplified Chinese (@zhmars)

**Comment by saulotoledo** [comment]
@p91paul I created this issue for us to remember those missing translations (and ask for help from those I mentioned above, if they are still available). Let me know if you require changes from my PR as well.

**Comment by tebaranowski** [comment]
Ok, I will add missing translation tomorrow.

**Comment by pervoj** [comment]
Thanks, I will update it as soon as possible.

**Comment by Vistaus** [comment]
Hmm, I don't see the new string.

**Comment by saulotoledo** [comment]
@Vistaus the missing translation is in [this line](https://github.com/arelange/gnome-shell-extension-hibernate-status/blob/master/extension.js#L192).
@pervoj, @Vistaus, if you have some time later, could you also comment on [this PR](https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/81)? There are a few more strings needing translation when that is ready (starting [here](https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/81/files#diff-40e552276ed87f7d6ceb3ab047fbbebe7d5309b4bc5aaee375a4046fb9b0da7dR68)).

**Comment by Vistaus** [comment]
@saulotoledo But I don't see the new string in the nl.po file.

**Comment by mskf1383** [comment]
Thank you for notice!

**Comment by saulotoledo** [comment]
@Vistaus, ah ok! That is really missing. We have to add it as @mskf1383 did in [his PR](https://github.com/arelange/gnome-shell-extension-hibernate-status/pull/87).

**Comment by tebaranowski** [comment]
@saulotoledo I created pull request with updated translation  in PO file and some minor grammar fixes. Sorry it took so long, I was AFK for some time.

**Comment by p91paul** [comment]
Most languages should be updated. Closing the issue, thanks to all!
